services:
  rate-limiter:
    build: .
    container_name: rate-limiter
    ports:
      - "8080:8080"
    environment:
      - CLIENT_ADDR
      - CLIENT_PASSWORD
      - CLIENT_DB
      - RATE_LIMIT_IP
      - RATE_LIMIT_TOKEN
      - BLOCK_TIME
      - REFILL_INTERVAL
      - TOKENS_PER_REFILL
      - MAX_TOKENS_PER_IP
      - MAX_TOKENS_PER_TOKEN

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - CLIENT_PASSWORD
